### ISSUE TITLE
Remove GitHub pages

### ISSUE THREAD

**Issue by TheEvilSkeleton** [gasinvein/proton-flatpak#11]
Just a little notification that GitHub is trying to deploy a website: https://github.com/gasinvein/proton-flatpak/deployments/activity_log?environment=github-pages

**Comment by gasinvein** [comment]
Github pages were used to store static index for the docker registry (at DockerHub), this was needed to allow flatpak installing apps from the docker registry.

**Comment by TheEvilSkeleton** [comment]
Oh okay.

**Comment by gasinvein** [comment]
This repository is obsolete anyway. Probably I should archive it.
